In [16]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()

In [17]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  flower
0                5.1               3.5  ...               0.2  setosa
1                4.9               3.0  ...               0.2  setosa
2                4.7               3.2  ...               0.2  setosa
3                4.6               3.1  ...               0.2  setosa
4                5.0               3.6  ...               0.2  setosa

[5 rows x 5 columns]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [19]:
from sklearn.svm import SVC
model=SVC(kernel='rbf', C=30, gamma='auto')
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9333333333333333

In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
kernel = ['rbf', 'linear']
C = [1,10,20]
avg_scores={}
for kval in kernel:
  for cval in C:
    cv_scores = cross_val_score(SVC(kernel=kval, C=cval, gamma='auto'),iris.data, iris.target, cv=5)
    avg_scores[kval + ' ' + str(cval)] = np.average(cv_scores)

avg_scores

{'linear 1': 0.9800000000000001,
 'linear 10': 0.9733333333333334,
 'linear 20': 0.9666666666666666,
 'rbf 1': 0.9800000000000001,
 'rbf 10': 0.9800000000000001,
 'rbf 20': 0.9666666666666668}

# GridSearchCV

In [21]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00149517, 0.00072269, 0.00078235, 0.00065193, 0.00077543,
        0.00066934]),
 'mean_score_time': array([0.00096335, 0.00037651, 0.00041003, 0.00034986, 0.00038729,
        0.00044303]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'rank_test_score': array([1, 1, 1, 4, 5, 6], dtype=int32),
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'std_fit_time': array([5.50859766e-04, 6.64416416e-05, 1.87334506e-05, 4.20192302e-05,
        1.97203154e-05, 2.42168500e-05]),
 'std_score_time': array([7.06907534e-04, 1.97178940e-05, 2.28341777e-05, 1.59613003e-05,
        1.94164671e-05, 2.06934438e-04]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 ])}

In [23]:
df = pd.DataFrame(clf.cv_results_)
df

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001495      0.000551  ...        0.016330                1
1       0.000723      0.000066  ...        0.016330                1
2       0.000782      0.000019  ...        0.016330                1
3       0.000652      0.000042  ...        0.038873                4
4       0.000775      0.000020  ...        0.036515                5
5       0.000669      0.000024  ...        0.042164                6

[6 rows x 15 columns]

# RandomizedSearchCV

In [24]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf', 'linear']
}, cv=5, return_train_score=False, n_iter=2)

rs.fit(iris.data, iris.target)
rs.cv_results_

{'mean_fit_time': array([0.00107846, 0.00091481]),
 'mean_score_time': array([0.00093517, 0.00041118]),
 'mean_test_score': array([0.98, 0.98]),
 'param_C': masked_array(data=[10, 1],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 10, 'kernel': 'rbf'}, {'C': 1, 'kernel': 'linear'}],
 'rank_test_score': array([1, 1], dtype=int32),
 'split0_test_score': array([0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'std_fit_time': array([0.00012151, 0.00027519]),
 'std_score_time': array([8.33612205e-04, 3.54324342e-05]),
 'std_test_score': array([0.01632993, 0.01632993])}

In [25]:
df = pd.DataFrame(rs.cv_results_)
df

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001078      0.000122  ...         0.01633                1
1       0.000915      0.000275  ...         0.01633                1

[2 rows x 15 columns]